version: '3.8'

services:
  db:
    image: postgres:13
    container_name: subapp-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subapp
    ports:
      - "5432:5432"
    volumes:
      - subapp-data:/var/lib/postgresql/data
    networks:
      - subapp-network

  app:
    build: .
    container_name: subapp
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - subapp-network
    restart: always

volumes:
  subapp-data:

networks:
  subapp-network:
    driver: bridge